name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project & doc dependencies
        run: |
          pip install -e .
          pip install "sphinx==7.2.6" "docutils<0.21" sphinx-autodoc-typehints furo sphinx-copybutton
          # Add extra Sphinx extensions here if you use them
          pip install myst-parser
          #pip install pylint
          pip install pyreverse
      - name: Copy README and CONTRIBUTING into docs
        run: |
          pwd
          ls
          cp README.md docs/source/README.md
          cp CONTRIBUTING.md docs/source/CONTRIBUTING.md

      - name: Generate class diagrams with pyreverse
        run: |
          pyreverse -o mmd -p mesoSPIM mesoSPIM --only-classnames -d docs 

      - name: Inject into docs/README
        run: |
          python scripts/inject_mermaid.py

      - name: Generate API docs with sphinx-apidoc
        run: |
          sphinx-apidoc -o docs/source/api mesoSPIM

      - name: Build HTML documentation
        run: |
          sphinx-build -b html --keep-going docs/source docs/build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
